stages:
  - test
  - build
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  IMAGE_NAME: christianwdc/product-api

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  only:
    - main
  cache:
    paths:
      - .m2/repository
  before_script:
    - cp settings-ci.xml /root/.m2/settings.xml
    - mvn install:install-file -Dfile=product-core-0.3.0.jar -DgroupId=sn.isi.l3gl.core -DartifactId=product-core -Dversion=0.3.0 -Dpackaging=jar
  script:
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  only:
    - main
  cache:
    paths:
      - .m2/repository
  before_script:
    - cp settings-ci.xml /root/.m2/settings.xml
    - mvn install:install-file -Dfile=product-core-0.3.0.jar -DgroupId=sn.isi.l3gl.core -DartifactId=product-core -Dversion=0.3.0 -Dpackaging=jar
  script:
    - mvn clean package -DskipTests
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

docker:
  stage: docker
  image: docker:24
  only:
    - main
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest